// Command gen-go generates the typed cs bindings from the embedded cmdlet catalog
// (go-teams/spec). Each cmdlet becomes a <GoName>Params struct + a Service method
// that dispatches through teamsapi to the right /Skype.Policy REST operation:
//
//	New-CsTeamsMeetingPolicy -> cs.NewCsTeamsMeetingPolicyParams + svc.NewCsTeamsMeetingPolicy
//
// Output: cs/zz_generated_cs.go (do not edit). Re-run after refreshing the catalog.
//
//	go run ./cmd/gen-go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/terraprovider/go-teams/spec"
)

// verbKind maps a cmdlet verb to the teamsapi policy operation kind.
var verbKind = map[string]string{
	"New":    "PolicyNew",
	"Get":    "PolicyGet",
	"Set":    "PolicySet",
	"Remove": "PolicyRemove",
}

func main() {
	cat, err := spec.Teams()
	if err != nil {
		fatal("load catalog: %v", err)
	}
	byNoun := cat.ByNoun()
	validated := spec.ValidatedPolicies()

	// Scope: catalog nouns that are readable (have Get) and whose {PolicyName}
	// resolves to a live-validated /Skype.Policy configuration.
	var nouns []string
	for noun, verbs := range byNoun {
		if _, ok := verbs["Get"]; !ok {
			continue
		}
		if !validated[spec.PolicyName(noun)] {
			continue
		}
		nouns = append(nouns, noun)
	}
	sort.Strings(nouns)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen-go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package cs holds the generated MicrosoftTeams -Cs* config/policy bindings.\n")
	fmt.Fprintf(&b, "package cs\n\n")
	fmt.Fprintf(&b, "import (\n\t%q\n\n\t%q\n)\n\n", "context", "github.com/terraprovider/go-teams/teamsapi")
	fmt.Fprintf(&b, "// Service wraps a *teamsapi.Client with the generated cmdlet methods.\n")
	fmt.Fprintf(&b, "type Service struct{ C *teamsapi.Client }\n\n")
	fmt.Fprintf(&b, "// New wraps a *teamsapi.Client.\nfunc New(c *teamsapi.Client) *Service { return &Service{C: c} }\n\n")

	done := map[string]bool{} // guard against emitting the same method twice
	policyN, autorestN := 0, 0

	// (a) /Skype.Policy CRUD bindings.
	for _, noun := range nouns {
		policyName := spec.PolicyName(noun)
		verbs := byNoun[noun]
		for _, verb := range []string{"New", "Get", "Set", "Remove"} {
			cm, ok := verbs[verb]
			if !ok || done[cm.Cmdlet] {
				continue
			}
			emitCmdlet(&b, cm, policyOp(cm, policyName))
			done[cm.Cmdlet] = true
			policyN++
		}
	}

	// (b) typed AutoRest bindings (non-/Skype.Policy ops with a known route).
	routes, err := spec.AutoRestRoutes()
	if err != nil {
		fatal("load autorest routes: %v", err)
	}
	byName := map[string]spec.Cmdlet{}
	for _, cm := range cat.Cmdlets {
		byName[cm.Cmdlet] = cm
	}
	var arNames []string
	for name := range routes {
		arNames = append(arNames, name)
	}
	sort.Strings(arNames)
	for _, name := range arNames {
		cm, ok := byName[name]
		if !ok || done[name] {
			continue
		}
		emitCmdlet(&b, cm, autorestOp(cm, routes[name]))
		done[name] = true
		autorestN++
	}

	// (c) Grant-Cs*Policy assignment bindings (assign a policy to Global/Group/User).
	grantN := 0
	for _, cm := range cat.Cmdlets {
		if cm.Verb != "Grant" || !strings.HasPrefix(cm.Noun, "Cs") || done[cm.Cmdlet] {
			continue
		}
		emitCmdlet(&b, cm, grantOp(cm, spec.PolicyName(cm.Noun)))
		done[cm.Cmdlet] = true
		grantN++
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		os.WriteFile("cs/zz_generated_cs.go.broken", b.Bytes(), 0o644)
		fatal("gofmt: %v (wrote cs/zz_generated_cs.go.broken)", err)
	}
	if err := os.MkdirAll("cs", 0o755); err != nil {
		fatal("mkdir: %v", err)
	}
	if err := os.WriteFile("cs/zz_generated_cs.go", out, 0o644); err != nil {
		fatal("write: %v", err)
	}
	fmt.Printf("gen-go: %d policy + %d autorest + %d grant methods -> cs/zz_generated_cs.go\n", policyN, autorestN, grantN)
}

func emitCmdlet(b *bytes.Buffer, cm spec.Cmdlet, opLit string) {
	goName := strings.ReplaceAll(cm.Cmdlet, "-", "") // New-CsTeamsMeetingPolicy -> NewCsTeamsMeetingPolicy
	pstruct := goName + "Params"

	// params struct
	fmt.Fprintf(b, "// %sParams are the bound parameters for %s.\n", goName, cm.Cmdlet)
	fmt.Fprintf(b, "type %s struct {\n", pstruct)
	seen := map[string]bool{}
	for _, p := range cm.Parameters {
		field := exportName(p.Name)
		if seen[field] {
			continue
		}
		seen[field] = true
		comment := ""
		if len(p.ValidateSet) > 0 {
			comment = " // one of: " + strings.Join(p.ValidateSet, ", ")
		}
		fmt.Fprintf(b, "\t%s %s `ps:%q`%s\n", field, fieldGoType(p), p.Name, comment)
	}
	fmt.Fprintf(b, "}\n\n")

	// params() -> only bound parameters
	fmt.Fprintf(b, "func (p %s) params() map[string]any {\n\tm := map[string]any{}\n", pstruct)
	seen = map[string]bool{}
	for _, p := range cm.Parameters {
		field := exportName(p.Name)
		if seen[field] {
			continue
		}
		seen[field] = true
		fmt.Fprintf(b, "\t%s\n", boundCheck(field, p.Name, fieldGoType(p)))
	}
	fmt.Fprintf(b, "\treturn m\n}\n\n")

	// method
	fmt.Fprintf(b, "// %s runs %s.\n", goName, cm.Cmdlet)
	fmt.Fprintf(b, "func (s *Service) %s(ctx context.Context, p %s) (*teamsapi.Result, error) {\n", goName, pstruct)
	fmt.Fprintf(b, "\treturn s.C.Invoke(ctx, %s, p.params())\n}\n\n", opLit)
}

func policyOp(cm spec.Cmdlet, policyName string) string {
	return fmt.Sprintf("teamsapi.Op{CmdletName: %q, Transport: teamsapi.ConfigAPI, Kind: teamsapi.%s, PolicyName: %q}",
		cm.Cmdlet, verbKind[cm.Verb], policyName)
}

func autorestOp(cm spec.Cmdlet, r spec.AutoRestRoute) string {
	m := r.Method
	if m == "" || m == "?" {
		m = "GET"
	}
	return fmt.Sprintf("teamsapi.Op{CmdletName: %q, Transport: teamsapi.ConfigAPI, Kind: teamsapi.AutoRest, Method: %q, Path: %q}",
		cm.Cmdlet, m, r.Path)
}

func grantOp(cm spec.Cmdlet, policyType string) string {
	return fmt.Sprintf("teamsapi.Op{CmdletName: %q, Transport: teamsapi.ConfigAPI, Kind: teamsapi.PolicyGrant, PolicyName: %q}",
		cm.Cmdlet, policyType)
}

// fieldGoType is the Params struct field type. The lookup key "Identity" is typed
// as `any` (not string) so the tf-msadmin/genframework contract — which passes an
// `any` identity through to <Params>{Identity: ...} — composes without assertions.
func fieldGoType(p spec.Param) string {
	if p.Name == "Identity" {
		return "any"
	}
	return goType(p)
}

// goType maps a catalog parameter type to a Go type. Nullable value types become
// pointers so an explicit false / 0 is distinguishable from "unset" (these config
// APIs are tri-state).
func goType(p spec.Param) string {
	switch p.Type {
	case "switch":
		return "bool"
	case "bool":
		return "*bool"
	case "int":
		return "*int64"
	case "float":
		return "*float64"
	case "string":
		return "string"
	case "stringArray", "array":
		return "[]string"
	default:
		return "any"
	}
}

func boundCheck(field, psName, gt string) string {
	switch gt {
	case "bool": // switch
		return fmt.Sprintf("if p.%s { m[%q] = true }", field, psName)
	case "string":
		return fmt.Sprintf("if p.%s != \"\" { m[%q] = p.%s }", field, psName, field)
	case "[]string":
		return fmt.Sprintf("if len(p.%s) > 0 { m[%q] = p.%s }", field, psName, field)
	case "*bool", "*int64", "*float64":
		return fmt.Sprintf("if p.%s != nil { m[%q] = *p.%s }", field, psName, field)
	default: // any
		return fmt.Sprintf("if p.%s != nil { m[%q] = p.%s }", field, psName, field)
	}
}

func exportName(name string) string {
	if name == "" {
		return "X"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func fatal(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "gen-go: "+f+"\n", a...)
	os.Exit(1)
}
