// Command gen-models generates typed model structs (one per in-scope policy type)
// for teamsapi.Result.Decode. Fields are the union of a noun's Get/Set/New cmdlet
// parameters (the settable/queryable surface) plus the standard read-back fields,
// typed from the embedded catalog — no tenant data involved.
//
// Output: models/zz_generated_models.go (do not edit).
//
//	go run ./cmd/gen-models
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/terraprovider/go-teams/spec"
)

// common/write-only params that are not read-back object fields.
var skipParams = map[string]bool{
	"Filter": true, "Force": true, "Confirm": true, "WhatIf": true,
	"Instance": true, "AsJob": true, "InputObject": true,
}

func main() {
	cat, err := spec.Teams()
	if err != nil {
		fatal("load catalog: %v", err)
	}
	byNoun := cat.ByNoun()
	validated := spec.ValidatedPolicies()

	var nouns []string
	for noun, verbs := range byNoun {
		if _, ok := verbs["Get"]; ok && validated[spec.PolicyName(noun)] {
			nouns = append(nouns, noun)
		}
	}
	sort.Strings(nouns)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen-models; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package models holds typed structs for teamsapi.Result.Decode, one per\n")
	fmt.Fprintf(&b, "// policy/config type. Fields are derived from the cmdlet catalog; use\n")
	fmt.Fprintf(&b, "// Result.Value ([]map[string]any) for fields not modelled here.\n")
	fmt.Fprintf(&b, "package models\n\n")
	fmt.Fprintf(&b, "import \"encoding/json\"\n\n")

	count := 0
	for _, noun := range nouns {
		emitModel(&b, spec.PolicyName(noun), byNoun[noun])
		count++
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		os.WriteFile("models/zz_generated_models.go.broken", b.Bytes(), 0o644)
		fatal("gofmt: %v (wrote .broken)", err)
	}
	if err := os.MkdirAll("models", 0o755); err != nil {
		fatal("mkdir: %v", err)
	}
	if err := os.WriteFile("models/zz_generated_models.go", out, 0o644); err != nil {
		fatal("write: %v", err)
	}
	fmt.Printf("gen-models: %d models -> models/zz_generated_models.go\n", count)
}

func emitModel(b *bytes.Buffer, name string, verbs map[string]spec.Cmdlet) {
	// union of fields across Get/Set/New, plus standard read fields
	type fld struct {
		gotype string
		order  int
	}
	fields := map[string]fld{}
	add := func(p spec.Param) {
		if skipParams[p.Name] || p.IsSwitch {
			return
		}
		if _, ok := fields[p.Name]; !ok {
			fields[p.Name] = fld{gotype: modelType(p), order: len(fields)}
		}
	}
	for _, v := range []string{"Get", "Set", "New"} {
		if cm, ok := verbs[v]; ok {
			for _, p := range cm.Parameters {
				add(p)
			}
		}
	}
	// standard read-back fields (present on every /Skype.Policy instance)
	for _, s := range []struct{ n, t string }{
		{"Identity", "string"}, {"ConfigId", "string"},
		{"Key", "json.RawMessage"}, {"ConfigMetadata", "json.RawMessage"},
	} {
		if _, ok := fields[s.n]; !ok {
			fields[s.n] = fld{gotype: s.t, order: len(fields)}
		}
	}

	names := make([]string, 0, len(fields))
	for n := range fields {
		names = append(names, n)
	}
	sort.Strings(names)

	fmt.Fprintf(b, "// %s models a %s instance.\n", name, name)
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, n := range names {
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", exportName(n), fields[n].gotype, n+",omitempty")
	}
	fmt.Fprintf(b, "}\n\n")
}

// modelType maps a catalog parameter type to a Go type for JSON decoding.
func modelType(p spec.Param) string {
	switch p.Type {
	case "bool":
		return "*bool"
	case "int":
		return "*int64"
	case "float":
		return "*float64"
	case "string":
		return "string"
	case "stringArray", "array":
		return "[]string"
	default:
		return "json.RawMessage"
	}
}

func exportName(name string) string {
	if name == "" {
		return "X"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func fatal(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "gen-models: "+f+"\n", a...)
	os.Exit(1)
}
